[tool.poetry]
name = "epimodel"
version = "0.1.1"
description = ""
authors = ["Tomas Gavenciak <gavento@gmail.com>"]
packages = [
    { include = "epimodel" },
]

[tool.poetry.dependencies]
python = ">=3.6.9"
numpy = "^1.18.2"
pandas = "^1.0.3"
tables = ">=3.2"
unidecode = "^1.1.1"
pyyaml = "^5.3"
requests = "^2.23"
plotly = "^4.6.0"

# Optional inference toolkits
jupyter = { version = "^1.0.0", optional = true }
pymc3 = { version = "^3.8", optional = true }
pyro-ppl = { version = "^1.3.0", optional = true }
seaborn = { version = "^0.10.0", optional = true }
tqdm = "^4.45.0"
scipy = "^1.4.1"
click = "^7.1.1"
luigi = "^2.8.13"

[tool.poetry.extras]
pymc3 = ["pymc3", "jupyter", "seaborn"]
pyro = ["pyro-ppl", "jupyter", "seaborn"]

[tool.poetry.dev-dependencies]
pytest = "^5.4.1"
black = "^19.10b0"
pre-commit = "^2.2.0"

[tool.black]
line-length = 88
target-version = ['py37']

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
